services:
  - type: web
    name: juegos360
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: gunicorn juegos360.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: *.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: juegos360-db
          property: connectionString
    healthCheckPath: /

